# Dockerfileでyarn installした場合、node_modulesがSYNCされないので
# Dockerを再起動下場合、node_modulesが消えてしまう。それを防ぐために、イメージビルド時にnode_modulesをマウントすることで回避する。
# https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds/32785014#32785014
version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/home/app/src:cached
      - node_modules:/src/node_modules
    ports:
      - "3000:3000"
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
