# node_modulesは匿名ボリュームして宣言している。匿名ボリュームにすると、Docker内で領域を確保する。
# そうすることで、ソース内のnode_modulesと連携を切ることでき、コンテナ内でnode_modulesを管理できる。
# そうしないと、node_modulesと強制同期してしまい、コンテナ内のnode_modulesが空になっていまう。
version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/home/app/src:cached
      - /home/app/src/node_modules
    working_dir: /home/app/src
    ports:
      - "3000:3000"
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true
